language: node_js

node_js: stable

install:
  - npm install
script:
  - npm run build
after_script:
  - cp -r dist docs
  - git config user.name "xiaofuyesnew"
  - git config user.email "xiaofuyesnew@qq.com"
  - git add -A
  - git commit -m 'deploy'
  - git push -f "https://${Travis_Token}@https://github.com/xiaofuyesnew/my-radar.git" master:master